### ISSUE TITLE
Can't manage to publish for review

### ISSUE THREAD

**Issue by benma** [terranpro/magit-gerrit#22] opened 2015-07-30 13:41 UTC
Hi

I have a local branch (not tracking any remote) with one commit. I want to publish it for review on gerrit.

`R P` does not work: `magit-gerrit-push-review: Couldn't find a commit at point`.

I don't have commits in my magit status buffer, as I am not tracking a remote.

When I do the same in the magit commit log buffer, I get `Wrong type argument: stringp, nil`.

I am using `Magit 2.1.0` on `Emacs 25.0.50.1`, and magit-gerrit from melpa (20150710.15).

Am I doing it wrong?

**Comment by louxiu** [comment] 2015-08-01 03:15
hi benma
When you `R P`, is your cursor on the line of the commit that you want to publish?

**Comment by benma** [comment] 2015-08-01 07:18
Thanks for the response. As I said:

>  don't have commits in my magit status buffer, as I am not tracking a remote.
> When I do the same in the magit commit log buffer, I get `Wrong type argument: stringp, nil.`

In which buffer exactly should I do this? The `R` key is not even defined in the commit log buffer, for example.

**Comment by louxiu** [comment] 2015-08-01 08:27
> In which buffer exactly should I do this?

magit status buffer

To enable `magit-gerrit-mode`, a gerrit remote is required. I don't think `magit-gerrit-mode` will be enabled automaticlly when there is not a gerrit remote.

Below is a typical gerrit remote in .git/config.
>
[remote "review"]
	url = ssh://username@your-gerrit-repo:29418/project-name
	push = HEAD:refs/for/master
	receivepack = git receive-pack --reviewer=xxx@yyy.com 

`(setq-default magit-gerrit-remote "review")`, this will let magit-gerrit use remote `review` as your gerrit remote.

**Comment by benma** [comment] 2015-08-01 13:11
Thanks. I have stop magit-gerrit successfully, I can see the reviews,
download patchsets, etc.

As I said, I don't have a commit shown in my magit-status buffer. I am
simply working in my local branch. Doing `git review` in the shell does the
right thing and pushes my commit for review.

**Comment by louxiu** [comment] 2015-08-02 03:04
I don't quite understand... 

As I known, if you want to push review in `magit status buffer`, a commit is required. To show a unpushed commit in `magit status buffer`, a remote branch is required.

**Comment by benma** [comment] 2015-08-03 09:10
Thanks again, and thanks for the patience.

If I have a remote branch and have one unpushed commit, it all works fine. 

This issue then turns into a feature request: I should be able to push a commit for review even if my current branch is not currently tracking a remote. There is no reason I shouldn't be able to use it when I am simply on my local branch.

Doing `git push ... HEAD:refs/for/master` works fine in that case, as does `git review` (with the [git review] tool](https://www.mediawiki.org/wiki/Gerrit/git-review).

Do you think that would be possible? A command that basically does what executing `git review` does?

**Comment by louxiu** [comment] 2015-08-04 02:16
@terranpro

**Comment by terranpro** [comment] 2015-08-06 11:26
Hi guys!  A little late to the party but I think we can definitely make this work.

I'm not sure how git review handles a branch without an upstream, does it just choose master by default?

I was thinking querying the user for a remote branch to push to would be a pretty good idea.
Could you check c2d3a8fa4b6d6b6ee2f8effe36b1361adeb1ea2c in master to see if/how that works for you?

**Comment by benma** [comment] 2015-08-06 14:47
@terranpro 

The variable `magit-gerrit-remote` is already there and contains the gerrit remote.

Querying the user for the remote would be nice if that variable is not set, but it is an orthogonal issue I think.

I tried the new commit. In the log buffer, I have to manually enable magit-gerrit-mode (it is done automatically in the status buffer). Trying to push a commit results in `magit-gerrit-push-review: Wrong type argument: stringp, nil`.

I think it would be better if you could still do `R P` in the status buffer, but if a commit can't be found, it should simply query the user, and default to HEAD.

**Comment by terranpro** [comment] 2015-08-07 05:50
@benma 

When I mentioned remote, I meant the remote branch we push the review to.
My place uses remote branches like `prod1_master`, `prod1_devel`, `prod2_devel`, ...
so if the current branch has is no tracked remote branch, I think querying the user is probably a safe approach?  My previous workflow was just to branch off a local then set its upstream or rebase back into a branch that was tracking a remote, which is why this feature didn't exist until now.

Anyways,  the latest commit in master should have enabled magit-gerrit in the log buffer

the line below should have done this:
`(add-hook 'magit-log-mode-hook #'magit-gerrit-check-enable t)`

The wrong type arg stringp shouldn't happen though, maybe you could check the backtrace w/ `toggle-debug-on-error` ?  Also, could you share the output of your `magit-version` ?

Thanks!

**Comment by devmem** [comment] 2016-01-21 22:25
This is still an issue on "latest" (from a day or two ago). The method we use for development is that we will checkout a branch based on current master, do development on the branch and then git review it. The branch has NO upstream branch, but gerrit handles it fine as it knows the *target* branch is master. There is no review branch - just a collection of reviews. Unfortunately, as there is no upstream branch, magit-gerrit doesn't "see" it as a commit for pushing. 

I am having *exactly* the same issues as benma had - make a commit, nothing shows in the magit buffer for me to gerrit push to. But then this appears expected as I don't have a remote branch tracking this one.

**Comment by louxiu** [comment] 2016-01-22 02:15
Could you use `ll` shortcut to jump to `magit-log`, then use `RP` to push commit?

**Comment by devmem** [comment] 2016-01-22 08:31
No, that doesn't work either. If I type `ll` have my cursor on the commit, the following happens:

`R` does not bring up the `magit-gerrit` window, it brings up the rename window. Bringing up the magit-status window and navigating to `R Gerrit` starts the `magit-gerrit` process. I can then press `P` which says:

`magit-gerrit-push-review: Wrong type argument: stringp, nil`

If I make a test commit on the master branch, `magit-gerrit` works as expected. 

I am running `magit-gerrit 20160111.1848` and `magit 20160118.1535`

**Comment by devmem** [comment] 2016-01-23 10:28
PS: enabling `toggle-debug-on-error` gives:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("refs/heads\\(.+\\)" nil)
  magit-gerrit-push-review(publish)
  magit-gerrit-create-review()
  call-interactively(magit-gerrit-create-review)
  magit-invoke-popup-action(80)
  call-interactively(magit-invoke-popup-action nil nil)
  command-execute(magit-invoke-popup-action)
```

**Comment by devmem** [comment] 2016-01-23 10:29
@terranpro

**Comment by louxiu** [comment] 2016-01-24 04:46
It's weird. `R` should bring up the `magit-gerrit` window in `magit-log` if it is ok in master branch. Could you check the return value of `(magit-gerrit-check-enable)`  in `magit-log`? If it is `nil`, please check which  condition it is mismatch.

**Comment by devmem** [comment] 2016-01-24 07:39
> Could you check the return value of `(magit-gerrit-check-enable)` in `magit-log`

How do I do that?

**Comment by devmem** [comment] 2016-01-24 19:00
BTW: this should be easy for you to reproduce. Create a branch that has no upstream, make an edit and stage and then you can't use the `magit-gerrit` commands automatically.

**Comment by louxiu** [comment] 2016-01-25 14:24
@devmem I know. You use the `master` branch? I think this is a bug in `master` branch. It has been fixed in `next` branch. Please checkout the `next` branch and try.

**Comment by devmem** [comment] 2016-01-25 16:44
OK. `R` still brings up the rename window in both the log window and the `magit` window. The errros are different though. Bringing up the `magit` window, pressing `?` and navigating to `R` then pressing `P` I get:

```
magit-invoke-popup-action: Wrong type argument: commandp, magit-gerrit-build-push-review-popup
```

Bringing up the log window and pressing `?` and navigating to `R` and pressing `P` gives:

```
Debugger entered--Lisp error: (void-function delete-if)
  (delete-if (quote null) (mapcar (function (lambda (k) (and (string-match "rb:\\(.*\\)" k) (match-string 1 k)))) args))
  (car-safe (delete-if (quote null) (mapcar (function (lambda (k) (and (string-match "rb:\\(.*\\)" k) (match-string 1 k)))) args)))
  (let ((rb (car-safe (delete-if (quote null) (mapcar (function (lambda ... ...)) args)))) (tp (car-safe (delete-if (quote null) (mapcar (function (lambda ... ...)) args))))) (magit-gerrit-push-review (quote publish) rb tp))
  magit-gerrit-create-review("rb:")
  call-interactively(magit-gerrit-create-review)
  magit-invoke-popup-action(80)
  call-interactively(magit-invoke-popup-action nil nil)
  command-execute(magit-invoke-popup-action)
```

`magit-version` prints `20160124.1041` (I upgraded packages as I removed the MELPA `magit-gerrit`)

By the way, this latest code doesn't work on the master branch either. Reverting to the MELPA version and I can push the commit on master to master, but not from the local untracked branch.

**Comment by louxiu** [comment] 2016-01-25 17:19
Hi, devmem. Let's try in log window first. `? R P`

`Debugger entered--Lisp error: (void-function delete-if)`, it seems that `cl` package is not bundled with your emacs(My Emacs version is 24.5 mac osx, bundled with `cl` as default), maybe you should install it manually or upgrade your emacs version?

Please try `next branch` again after you install `cl` package (or upgrade your emacs).

**Comment by devmem** [comment] 2016-01-25 17:40
I'm running Emacs 24.4.1 (Linux/Ubuntu) with `cl-lib` inbuilt. All I do to get that error is:
* Uninstall MELPA `magit-gerrit`
* Download `magit-gerrit.el` in `../site-lisp/` (which is on my include path)

I also have a number of other packages that depend on `cl-lib` which all work fine. Also, if I download the master version of `magit-gerrit.el` and replace the next version of it, I do not get this error.

**Comment by terranpro** [comment] 2016-01-29 03:17
Hi devmem,

I think I see the fix for the problem for the code in the `master` branch
Adding an extra null check will give the completion enabled popup, prompting for the remote branch to push to:

        (let* ((branch-merge (if (or (null branch-remote)
    				 (string= branch-remote "."))

I'll add this fix to the master branch and update the MELPA package.

I tried to tackle this problem in the `next` branch by using dynamic popups, which is where the symbol you pasted `magit-gerrit-build-push-review-popup` comes from.  It's not in the master branch yet so I think (hope?!) that error may have been some mixed up versions on your machine.

I've been planning to merge the next branch over to master soon, but was hoping a few people might check it out first and make sure the new popup experience isn't horrible.

Thanks for the report

**Closed** 2016-01-29 03:29 UTC

**Comment by devmem** [comment] 2016-01-29 07:39
Thanks @terranpro. I appreciate the work :)

This version is better, but still not right. In the magit-status buffer, placing the cursor on the Review line and pressing `R` brings up the popup. Pressing `P` at that point shows:

```
or: Couldn't find commit at point
```

Entering the log window, selecting a commit and pressing `R` brings up the `magit-gerrit` popup window, and pressing `P` brings up the `remote branch` window, but I am only allowed to select one of either 

```
refs/heads/HEAD
refs/heads/master
```

which then tries to push to `refs/publish/HEAD/<current-branch-name>`. Our way of working with `gerrit` is to push `HEAD` to `refs/for/<destination-branch>` (where `<destination-branch>` is normally `master`, do the review in the `refs/for` namespace (which is the default `gerrit` review namespace and then `cherry-pick` onto `<destination-branch>` when the review is complete.

I have the following in my `.git\config`

```
[remote "review"]
url = ssh://myusername@localhost:29418/test-project
push = HEAD:refs/for/master
```

If I had any idea how to write elisp, I'd try and do it myself....

**Comment by devmem** [comment] 2016-01-29 07:55
Let me know if you want to open another issue here.

**Comment by devmem** [comment] 2016-01-29 16:57
@terranpro I need to test this a bit more. I only had a quick chance to test and it may well have been the way I was trying to drive the system. I'll test it more thoroughly this weekend from a clean repo and file a new issue if I find one...

**Comment by terranpro** [comment] 2016-02-01 05:20
Hey @devmem, I think refs/for/ and refs/publish/ are the same 'magic' branches for gerrit.

https://gerrit-review.googlesource.com/Documentation/access-control.html#references

Did pushing the review to refs/publish/master (for example) not create/update a review as it does with your normal workflow ?

Feel free to reopen or create a new issue if it's still broke! =)

**Comment by terranpro** [comment] 2016-02-01 05:32
Ah, one more comment about the original point you made, pressing 'R' 'P' from the point on the 'review' line.

The magit-gerrit internals are such that the point needs to be on a 'commit' line since it uses magit mode's properties to get info on the commit at point to run git push.  If it's on the review line (currently anyways), it bails out because it doesn't know which commit matches that review and what it needs to push.

From the review line, it's really just about verify/code review/submit/abandon/comment/view+download patchset; and the commit lines being about push review/draft.  In the `next` branch, the menus are context specific so it kind of guides your options a little more.

It would be neat to be able to update patchsets via the review lines though

**Comment by devmem** [comment] 2016-02-01 05:50
Thanks - that makes sense. I hadn't realised the `refs/for` and `refs/publish` were equivalent. Looks to be working for me now via the log buffer :). The only thing missing is the ability to press `R` in the `magit` window after you've committed a change. You currently have to `ll` to visit the log window before you can press `R` to bring up the `magit-gerrit` window - or am I missing something?
